export const COUNTER_INCREMENT="INCREMENT"
export const COUNTER_DECREMENT="DECREMENT"
export const COUNTER_INCREMENT_="INCREMENT_"
export const COUNTER_DECREMENT_="DECREMENT_"

export const GET_CONTACTS = "GET_CONTACTS";
export const GET_CONTACTS_SUCCESS = "GET_CONTACTS_SUCCESS";
export const GET_CONTACTS_FAILURE = "GET_CONTACTS_FAILURE";
